### ISSUE TITLE
:simple_smile:

### ISSUE THREAD

**Issue by sqwishy** [Shimmi/slack-emoji-style-chooser#4]
:simple_smile: is different now. Can/should we do something about it? I miss the old one. I don't think it was part of any other icon sets because it was Slack's own sprite. And it has its own sprite now not part of the sprite sheets I think.

**Comment by Shimmi** [comment]
Ho @sqwishy,
To be honest, I do not remember the look of the old simple smile smiley. Although I remember those days we were asking for it...! :) Do you have some reference, maybe? Although not sure If we shall do something with it as it was replaced with a proper one from the Emoji/Unicode set...

**Comment by sqwishy** [comment]
It's the second icon in here:

![](https://cdn-images-1.medium.com/max/372/1*yaijXcx1UF2VWx0cFyUFuA.png)

But I don't know where to find a higher quality image.

**Comment by sqwishy** [comment]
The icon there is very close to https://emojipedia.org/emojione/1.0/slightly-smiling-face/ and the slack people told me that that's what they used.

**Comment by Shimmi** [comment]
Hi @sqwishy,
Sorry for late response. Thanks for the additional info! As I can see the icon is part of the EmojiOne v1.0 released back in 2014 which unfortunately does not have all the emoji we have today. So there will either have to be a lot of blank space or the emoji set would have to be combined with another one 😞.

But you can add this icon as a custom icon in your workspace! Hope this satisfy your needs! 😃
See https://get.slack.help/hc/en-us/articles/206870177-Create-custom-emoji
