### ISSUE TITLE
Emojione stopped displaying

### ISSUE THREAD

**Issue by rubin110** [Shimmi/slack-emoji-style-chooser#5]
Over the last few days I've noticed that Emojione stopped playing in Slack on the Web. I'm not sure why, and I don't know enough about how Slack deals with printing images in chat to debug more, but here's a screen shot.

![20180712112620-selection](https://user-images.githubusercontent.com/222551/42652611-c63d6cda-85c7-11e8-91a0-e0710c1f5b33.png)

Thanks!

**Comment by Shimmi** [comment]
Hi @rubin110,
thanks for reporting this! I've just pushed an updated version to the store (v0.10).

The issue was caused by a new release of the emoji assets library iamcal/emoji-data which removed the EmojiOne assets.
